//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTU_Recruits.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUser()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaim>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogin>();
            this.AspNetUserRoles = new HashSet<AspNetUserRole>();
        }
    
        public string Id { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public byte[] UserPhoto { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ShortDescription { get; set; }
        public string UserRoles { get; set; }
        public string Work_Title1 { get; set; }
        public string Work_Title2 { get; set; }
        public string Work_TItle3 { get; set; }
        public string Work_Name1 { get; set; }
        public string Work_Name2 { get; set; }
        public string Work_Name3 { get; set; }
        public string Work_Description1 { get; set; }
        public string Work_Description2 { get; set; }
        public string Work_Description3 { get; set; }
        public Nullable<System.DateTime> Work_DateStart1 { get; set; }
        public Nullable<System.DateTime> Work_DateStart2 { get; set; }
        public Nullable<System.DateTime> Work_DateStart3 { get; set; }
        public Nullable<System.DateTime> Work_DateEnd1 { get; set; }
        public Nullable<System.DateTime> Work_DateEnd2 { get; set; }
        public Nullable<System.DateTime> Work_DateEnd3 { get; set; }
        public string Edu_Title1 { get; set; }
        public string Edu_Title2 { get; set; }
        public string Edu_Title3 { get; set; }
        public string Edu_School1 { get; set; }
        public string Edu_School2 { get; set; }
        public string Edu_School3 { get; set; }
        public string Edu_Description1 { get; set; }
        public string Edu_Description2 { get; set; }
        public string Edu_Description3 { get; set; }
        public Nullable<System.DateTime> Edu_DateStart1 { get; set; }
        public Nullable<System.DateTime> Edu_DateStart2 { get; set; }
        public Nullable<System.DateTime> Edu_DateStart3 { get; set; }
        public Nullable<System.DateTime> Edu_DateEnd1 { get; set; }
        public Nullable<System.DateTime> Edu_DateEnd2 { get; set; }
        public Nullable<System.DateTime> Edu_DateEnd3 { get; set; }
        public string Skill1 { get; set; }
        public string Skill2 { get; set; }
        public string Skill3 { get; set; }
        public string Hobbies_Desc { get; set; }
        public string Visibility { get; set; }
        public string Success { get; set; }
        public string CV_Category { get; set; }
        public string CompanyName { get; set; }
        public string PhysicalAddress { get; set; }
        public string ContactNumber { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyWebsite { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaim> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogin> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserRole> AspNetUserRoles { get; set; }
    }
}
